### ISSUE TITLE
New Features for fractal2.py

### ISSUE THREAD

**Issue by taylorschimek** [taylorschimek/udacity_projects#2]
## TODO

*Features to add to fractal drawer*

* [ ] initial prompts for which shape: triangle, square, etc.
* [ ] initial prompts for fill colors
* [ ] better explanation for what existing and new prompts mean.

:wink:
